I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/chapters/introduction.rpy", line 27, in script
    scene black with fadein
  File "game/code/chapters/introduction.rpy", line 27, in <module>
    scene black with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/chapters/introduction.rpy", line 27, in script
    scene black with fadein
  File "C:\Renpy\renpy\ast.py", line 1654, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Renpy\renpy\python.py", line 1083, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Renpy\renpy\python.py", line 1076, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/code/chapters/introduction.rpy", line 27, in <module>
    scene black with fadein
NameError: name 'fadein' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
ESMAUGUE 1.0
Thu Sep 29 19:50:15 2022
