I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/places/puzzle3.rpy", line 34, in script
    menu:
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/places/puzzle3.rpy", line 34, in script
    menu:
  File "C:\Renpy\renpy\ast.py", line 1899, in execute
    renpy.exports.say(None, "\n".join(narration), interact=False)
  File "C:\Renpy\renpy\exports.py", line 1362, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Espaço 233 1.0
Sat Nov 19 19:08:52 2022
