I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: "D:\\Ren'Py Games\\visual-novel\\game\\saves\\persistent.1665359705.tmp"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Renpy\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "C:\Renpy\renpy\main.py", line 663, in main
    renpy.persistent.update(True)
  File "C:\Renpy\renpy\persistent.py", line 397, in update
    save()
  File "C:\Renpy\renpy\persistent.py", line 413, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\Renpy\renpy\savelocation.py", line 494, in save_persistent
    l.save_persistent(data)
  File "C:\Renpy\renpy\savelocation.py", line 345, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "D:\\Ren'Py Games\\visual-novel\\game\\saves\\persistent.1665359705.tmp"

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Espaço 233 1.0
Sun Oct  9 20:57:11 2022
