I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/chapters/introduction.rpy", line 3, in script
    $ decompress("logos")
  File "game/code/chapters/introduction.rpy", line 3, in <module>
    $ decompress("logos")
  File "game/code/systems/compression.rpy", line 35, in decompress
    zip = zipfile.ZipFile(zip_name + ".zip", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'logos.zip'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/chapters/introduction.rpy", line 3, in script
    $ decompress("logos")
  File "C:\Renpy\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Renpy\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/code/chapters/introduction.rpy", line 3, in <module>
    $ decompress("logos")
  File "game/code/systems/compression.rpy", line 35, in decompress
    zip = zipfile.ZipFile(zip_name + ".zip", "r")
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'logos.zip'

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.2.22081402
Espaço 233 1.0
Sun Nov  6 18:53:22 2022
